export const businesses = {
  sipla: {
    name: 'Sipla Solutions',
    url: 'https://www.siplasolutions.com',
    description: 'Glass wool, rockwool, fiberglass and insulation solutions',
    color: '#1A5276',
    accent: '#2E86C1',
    bg: '#EBF5FB',
    label: 'Insulation & Materials',
  },
  greeneco: {
    name: 'Green Eco India',
    url: 'https://www.greenecoindia.com',
    description: 'BMS, e-rickshaw components, LED lighting and energy storage',
    color: '#1E8449',
    accent: '#27AE60',
    bg: '#EAFAF1',
    label: 'EV & Clean Energy',
  },
  lithion: {
    name: 'Lithion Power',
    url: 'https://www.lithionpower.com',
    description: 'Advanced BMS for EVs, energy storage and industrial applications',
    color: '#7D6608',
    accent: '#D4AC0D',
    bg: '#FEF9E7',
    label: 'BMS & Batteries',
  },
  sirona: {
    name: 'Sirona Robotics',
    url: 'https://www.sironarobotics.com',
    description: 'Robotics, embedded systems, ELV solutions and smart city tech',
    color: '#922B21',
    accent: '#E74C3C',
    bg: '#FDEDEC',
    label: 'Robotics & IoT',
  },
  zerovir: {
    name: 'ZeroVIR',
    url: 'https://www.zero-vir.com',
    description: 'Confidential, audit-proof liquidation of MCUs, PMICs, MOSFETs and active ICs',
    color: '#1B2631',
    accent: '#2ECC71',
    bg: '#F0F3F4',
    label: 'Semiconductor Liquidation',
  },
  inyx: {
    name: 'iNYX Batteries',
    url: 'https://www.inyxbatteries.com',
    description: 'Smart battery packs for drones, AMRs and autonomous vehicles with integrated BMS',
    color: '#154360',
    accent: '#1ABC9C',
    bg: '#E8F8F5',
    label: 'Autonomous Power Systems',
  },
}
